
-- ═══════════════════════════════════════════════════════════
-- PASSIVE FACILITATOR OS — Industrial engine
-- offers, offer_packs, link_events + enhance offer_share_links
-- ═══════════════════════════════════════════════════════════

-- 1. OFFERS — industrial offer entity
CREATE TABLE IF NOT EXISTS public.offers (
  id               UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  company_id       UUID NOT NULL,
  mission_id       UUID REFERENCES public.missions(id) ON DELETE SET NULL,
  title            TEXT NOT NULL,
  summary          TEXT,
  full_description TEXT,
  sector           TEXT,
  target_profile   TEXT,
  target_geo       TEXT,
  target_languages TEXT[] DEFAULT '{}',
  primary_cta      TEXT,
  reward_model     TEXT,
  status           TEXT NOT NULL DEFAULT 'draft',
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Companies can manage their offers"
  ON public.offers FOR ALL
  USING (auth.uid() = company_id)
  WITH CHECK (auth.uid() = company_id);

CREATE POLICY "Facilitators can view active offers"
  ON public.offers FOR SELECT
  USING (status IN ('active', 'ready'));

CREATE TRIGGER update_offers_updated_at
  BEFORE UPDATE ON public.offers
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 2. OFFER_PACKS — multi-format diffusion packs generated by OpenClaw
CREATE TABLE IF NOT EXISTS public.offer_packs (
  id                  UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  offer_id            UUID REFERENCES public.offers(id) ON DELETE CASCADE,
  shared_offer_id     UUID REFERENCES public.shared_offers(id) ON DELETE CASCADE,
  company_id          UUID NOT NULL,
  language            TEXT NOT NULL DEFAULT 'fr',
  whatsapp_short      TEXT,
  whatsapp_natural    TEXT,
  email_simple        TEXT,
  email_premium       TEXT,
  post_short          TEXT,
  private_message     TEXT,
  pitch_ultra_short   TEXT,
  status              TEXT NOT NULL DEFAULT 'draft',
  generated_by        TEXT DEFAULT 'openclaw',
  generated_at        TIMESTAMP WITH TIME ZONE,
  approved_at         TIMESTAMP WITH TIME ZONE,
  created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.offer_packs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Companies can manage their packs"
  ON public.offer_packs FOR ALL
  USING (auth.uid() = company_id)
  WITH CHECK (auth.uid() = company_id);

CREATE POLICY "Facilitators can view approved packs"
  ON public.offer_packs FOR SELECT
  USING (status = 'approved' OR status = 'active');

CREATE TRIGGER update_offer_packs_updated_at
  BEFORE UPDATE ON public.offer_packs
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 3. LINK_EVENTS — granular click/interest/conversion events per tracked link
CREATE TABLE IF NOT EXISTS public.link_events (
  id                UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  share_link_id     UUID REFERENCES public.offer_share_links(id) ON DELETE CASCADE,
  facilitator_id    UUID NOT NULL,
  event_type        TEXT NOT NULL,
  channel           TEXT,
  language          TEXT,
  visitor_fingerprint TEXT,
  ip_country        TEXT,
  metadata          JSONB DEFAULT '{}',
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.link_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Facilitators can view their link events"
  ON public.link_events FOR SELECT
  USING (auth.uid() = facilitator_id);

CREATE POLICY "Service can insert link events"
  ON public.link_events FOR INSERT
  WITH CHECK (true);

-- 4. ENHANCE offer_share_links with channel, language, attribution counters
ALTER TABLE public.offer_share_links
  ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'direct',
  ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'fr',
  ADD COLUMN IF NOT EXISTS qualified_interest_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS opportunity_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS introduction_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gain_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pack_id UUID REFERENCES public.offer_packs(id) ON DELETE SET NULL;

-- 5. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_offers_company_id ON public.offers(company_id);
CREATE INDEX IF NOT EXISTS idx_offers_status ON public.offers(status);
CREATE INDEX IF NOT EXISTS idx_offer_packs_offer_id ON public.offer_packs(offer_id);
CREATE INDEX IF NOT EXISTS idx_offer_packs_shared_offer_id ON public.offer_packs(shared_offer_id);
CREATE INDEX IF NOT EXISTS idx_offer_packs_company_id ON public.offer_packs(company_id);
CREATE INDEX IF NOT EXISTS idx_link_events_share_link_id ON public.link_events(share_link_id);
CREATE INDEX IF NOT EXISTS idx_link_events_facilitator_id ON public.link_events(facilitator_id);
CREATE INDEX IF NOT EXISTS idx_link_events_event_type ON public.link_events(event_type);
